version: '3.1'

services:
  wordpress:
    image: hansnok/wordpress_container:latest
    secrets:
      - wp_db_password
      - wp_db_user
      - wp_db_name
    environment:
      - WORDPRESS_DB_USER_FILE=/run/secrets/wp_db_user
      - WORDPRESS_DB_NAME_FILE=/run/secrets/wp_db_name
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/wp_db_password
      - WORDPRESS_DB_HOST=127.0.0.1
    ports:
      - "80:80"
      - "443:443"

  cloud_sql_proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.11
    secrets:
      - credencial_sql
      - instance_name
    command: ["/cloud_sql_proxy",
            "-instances=edtech-torneo:us-east4:wp-woocommerce=tcp:0.0.0.0:3306",
            "-credential_file=/run/secrets/credencial_sql"]
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - cloudsql:/cloudsql

volumes:
  cloudsql:

secrets:
  wp_db_password:
    file: ./wp_db_password.txt
  wp_db_user:
    file: ./wp_db_user.txt
  wp_db_name:
    file: ./wp_db_name.txt
  credencial_sql:
    file: ./credencial_sql.json
  instance_name:
    file: ./instance_name.txt